server:
  port: 8001
spring:
  application:
    name: modeler
  datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://10.208.204.46:3306/activiti?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123qwe